apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhdh-demo-deploy
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      parameters:
        - name: cluster.domain
          value: apps.ocp4.quitala.eu
        - name: github.pat
        - name: gitlab.version
          value: 8.11.4            
    path: installation
    repoURL: 'https://github.com/sgutierr/rhdh-jfrog-gitlab-demo.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true