# installation/templates/sw2/gitlab-shared-secrets-sa.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-shared-secrets
  namespace: {{ .Values.gitlab.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab
  namespace: {{ .Values.gitlab.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
# Agregar otros ServiceAccounts que GitLab pueda necesitar
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner
  namespace: {{ .Values.gitlab.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"