# installation/templates/sw1/gitlab-serviceaccount-rbac.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab
  namespace: {{ .Values.gitlab.namespaceName }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-installer-rolebinding
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subjects:
- kind: ServiceAccount
  name: gitlab
  namespace: {{ .Values.gitlab.namespaceName }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io